name: context
on:
  push
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: use context
        run: |
          echo "this workflow is triggeredby ${{github.actor}}"
          echo "${{github.repository}}"
          echo "${{github.ref_name}}"
      - name: json
        run: echo "${{toJson(github)}}"

      - name: print env
        run: printenv
