name: hello world
on:
  push:  
    branches: 
      - main
    paths:
      - .github/workflows/hello.yml
  pull_request:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: writen hello world
        run: |
          echo "Hello World"
          pwd
          git -v
          ifconfig
  bye:
    runs-on: windows-latest
    needs: hello
    steps:
      - name: says bye
        run: |
          pwd
          ipconfig
