name: if statement
on: 
  push:
    branches:
      - main
      - dev
jobs:
  if:
    runs-on: ubuntu-latest
    steps:
      - name: run if branch is main
        if: github.ref_name == 'main'
        run: echo "running for main branch"
      - name: run this step
        run: echo "running this step"
