name: input demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the options
        required: true
        default: dev
        options:
          - main
          - test
          - prod
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy the application to ${{inputs.environment}}"
