name: input demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the options
        required: true
        options:
          - main
          - test
          - prod
      tags:
        description: choose tags
        required: true
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy the ${{inputs.tags}} application to ${{inputs.environment}}"
