name: or-condition
on: 
  push
jobs:
  or:
    runs-on: ubuntu-latest
    steps:
      - name: run for satish or pavan
        if: github.actor == 'satish' || github.actor == 'pavan'
        run: echo "its triggered by satish or pavan"
     
