name: s3
on:
  push:
    branches:
      - main
jobs:
  s3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: passwords
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
          aws-region: eu-north-1

      - name: static
        run: |
          aws s3 sync ./ s3://saib-s3-demo/
