name: variable
on:
  push:
    branches:
      - main
jobs:
  var:
    runs-on: ubuntu-latest
    steps:
      - name: added variable
        run: |
          echo "hello, ${{vars.my_name}}"
          echo "hello, ${{secrets.passwords}}"
